version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of the workflow files
    schedule:
      interval: "monthly" # How often to check for updates (e.g., daily, weekly, monthly)
    commit-message:
      prefix: "Upgrade" # Prefix for the commit messages; can also use "feat" or customize
