name: Convert ZIP to APK

on:
  workflow_dispatch:

jobs:
  convert-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java
        run: sudo apt-get install -y openjdk-11-jdk

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Combine ZIP files
        run: cat ./zips/capybara_1.4.1.zip.* > ./zips/capybara_1.4.1.zip

      - name: Unzip files
        run: unzip ./zips/capybara_1.4.1.zip -d ./zips/capybara_1.4.1

      - name: Download apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          chmod +x apktool
          sudo mv apktool /usr/local/bin/

      - name: Convert ZIP to APK
        run: |
          mkdir -p output
          apktool d ./zips/capybara_1.4.1/apks/capybara_1.4.1.apks -o output/capybara

      - name: Build APK
        run: |
          apktool b output/capybara -o output/capybara.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: capybara-apk
          path: output/capybara.apk
          retention-days: 3
