name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Initialize Bubblewrap
        run: |
          printf "Y\nY\nY\n" | bubblewrap init \
            --manifest=https://braboobssiere.github.io/misc-codes/js/fairshare-manifest.json
 
      - name: Build APK
        run: bubblewrap build

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: fairshare-apk
          path: .
          retention-days: 7
