name: Clean Repository History

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write # Grant write access to the repository contents

jobs:
  clean-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for filter-branch to work

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Determine current branch
        id: get_branch
        run: |
          echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Clean up history with git filter-branch
        run: |
          # Create a new orphan branch
          git checkout --orphan latest_branch
          
          # Add all files to the new branch
          git add -A
          
          # Commit the changes
          git commit -m "Clear history"
          
          # Delete the old branch (either master or main)
          git branch -D ${{ env.CURRENT_BRANCH }}
          
          # Rename the new branch to the original branch name
          git branch -m ${{ env.CURRENT_BRANCH }}
          
          # Force push the changes to the remote repository
          git push -f origin ${{ env.CURRENT_BRANCH }}

      - name: Clean up and run garbage collection
        run: |
          git reflog expire --expire=now --all # Expire reflog entries
          git gc --prune=now --aggressive # Run garbage collection
