name: Clean Repository History

on:
  workflow_call: # Allows this workflow to be called from other workflows

permissions:
  contents: write # Grant write access to the repository contents

inputs:
  branch_name:
    description: 'The name of the branch to clean (default: current branch)'
    required: false
    type: string

jobs:
  clean-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for filter-branch to work

      - name: Set up Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Determine current branch
        id: get_branch
        run: |
          echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Clean up history with git filter-branch
        run: |
          # Use the provided branch name or fall back to the current branch
          BRANCH_NAME="${{ inputs.branch_name || env.CURRENT_BRANCH }}"
          
          # Create a new orphan branch
          git checkout --orphan latest_branch
          
          # Add all files to the new branch
          git add -A
          
          # Commit the changes
          git commit -m "Clear history"
          
          # Delete the old branch
          git branch -D "$BRANCH_NAME"
          
          # Rename the new branch to the original branch name
          git branch -m "$BRANCH_NAME"
          
          # Force push the changes to the remote repository
          git push -f origin "$BRANCH_NAME"

      - name: Clean up and run garbage collection
        run: |
          git reflog expire --expire=now --all # Expire reflog entries
          git gc --prune=now --aggressive # Run garbage collection
