name: Feed Parser
on:
  workflow_dispatch:
    inputs:
      feed-url:
        description: "Feed URL (RSS/Atom)"
        required: true
        type: string

jobs:
  parse-feed:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install feedparser

    - name: Parse and display feed
      run: |
        python -c "
        import feedparser
        import sys
        
        feed_url = '${{ github.event.inputs.feed-url }}'
        
        if not feed_url:
            print('Error: No feed URL provided')
            sys.exit(1)
            
        feed = feedparser.parse(feed_url)
        
        if not feed.entries:
            print('Error: No entries found or invalid feed')
            sys.exit(1)
            
        for i, item in enumerate(feed.entries):
            title = item.get('title', 'No title')
            updated = item.get('updated', item.get('published', 'No timestamp'))
            print(f'[{i+1}] {title}')
            print(f'   Last updated: {updated}\n')
        "
