name: Feed Parser
on:
  workflow_dispatch:
    inputs:
      feed-url:
        description: "Feed URL (RSS/Atom)"
        required: true
        type: string

jobs:
  parse-feed:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install feedparser

    - name: Parse and display feed
      run: |
        python -c "
        import feedparser
        
        feed_url = '${{ github.event.inputs.feed-url }}'

        def get_alternate_link(entry):
            for link in entry.get('links', []):
                if link.get('rel') == 'alternate':
                    return link['href']
            return entry.get('link', 'No link found')
        
        if not feed_url:
            print('Error: No feed URL provided')
            sys.exit(1)
            
        feed = feedparser.parse(feed_url)
        
        if not feed.entries:
            print('Error: No entries found or invalid feed')
            exit(1)
            
        for i, item in enumerate(feed.entries):
            title = item.get('title', 'No title')
            updated = item.get('updated', item.get('published', 'No timestamp'))
            link = get_alternate_link(item)
            print(f'[{i+1}] {title}')
            print(f'   Alternate link: {link}')
            print(f'   Last updated: {updated}\n')
        "
