name: Check Keepalive

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to check'
        required: true

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch HTML
        id: fetch_html
        run: |
          response=$(curl -s "${{ github.event.inputs.url }}")
          echo "html_content<<EOF" >> $GITHUB_ENV
          echo "$response" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check for keepalive
        id: check_keepalive
        run: |
          if echo "$html_content" | grep -q "keepalive/yes"; then
            echo "keepalive_found=true" >> $GITHUB_ENV
          else
            echo "keepalive_found=false" >> $GITHUB_ENV
          fi

      - name: Output result
        run: |
          echo "Keepalive found: ${{ env.keepalive_found }}"
