name: Check Keepalive Status

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to check'
        required: true

jobs:
  check-keepalive:
    runs-on: ubuntu-latest
    steps:
    - name: Check HTML source
      id: check_html
      run: |
        HTML_CONTENT=$(curl -sL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0" "${{ inputs.url }}")
        if echo "$HTML_CONTENT" | grep -q "keepalive/yes"; then
          echo "result=yes" >> $GITHUB_OUTPUT
        else
          echo "result=no" >> $GITHUB_OUTPUT
        fi
