name: Check HTML for keepalive flag

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to check'
        required: true
        default: 'https://example.com'

jobs:
  check-html:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
      
    steps:
      - name: Fetch HTML source
        id: fetch
        run: |
          echo "Fetching HTML for URL: ${{ github.event.inputs.url }}"
          # Fetch the HTML source content and output to a file
          curl -s "${{ github.event.inputs.url }}" -o html_source.txt
          
          # Fail if curl didn't return any content.
          if [ ! -s html_source.txt ]; then
            echo "No content fetched from URL!"
            exit 1
          fi

      - name: Check for keepalive/yes
        id: check
        run: |
          echo "Scanning the HTML source for 'keepalive/yes'"
          # Check if the file contains the pattern "keepalive/yes"
          if grep -q "keepalive/yes" html_source.txt; then
            echo "Result=Found keepalive/yes" >> $GITHUB_OUTPUT
          else
            echo "Result=No keepalive/yes found" >> $GITHUB_OUTPUT
          fi
          
      - name: Output result
        run: |
          echo "Check completed: ${{ steps.check.outputs.Result }}"
