name: Run Mangadex Exporter
on: [workflow_dispatch]

jobs:
  run-exporter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to directory
        run: cd mangadex-exporter
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: pip install uv
        
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e .
        
      - name: Restore credentials + Run exporter
        env:
          APP_CONFIG: ${{ secrets.CREDENTIALS_ENV }}
        run: |
          echo "$APP_CONFIG" > credentials.env
          echo "Configuration imported"
          uv run python -m mangadex_exporter
        
