name: Mirror Nitter Feed
on:
  schedule:
    - cron: '0 */3 * * *'  # Schedule to run every 3 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can choose the version you need

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Fetch combined Nitter RSS feed
        run: |
          # Create a JavaScript file to handle Puppeteer
          echo '
          const puppeteer = require("puppeteer");
          const fs = require("fs");
          
          async function fetchFeed() {
            const browser = await puppeteer.launch({ headless: true });
            const page = await browser.newPage();
            
            // Simulate browser to handle verification
            await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");

            // Go to Nitter and wait for the page to load
            await page.goto("https://nitter.poast.org/yuki_sakuna,ksononair,95rn16,hanamiya_rica/rss", {
              waitUntil: "networkidle2", 
              timeout: 0 
            });

            // Get the cookies from the page
            const cookies = await page.cookies();
            const cookieHeader = cookies.map(cookie => `${cookie.name}=${cookie.value}`).join("; ");

            // Save cookies to a file
            fs.writeFileSync("cookies.txt", cookieHeader);

            // Now download the RSS feed
            const response = await page.goto("https://nitter.poast.org/yuki_sakuna,ksononair,95rn16,hanamiya_rica/rss");
            const feedContent = await response.text();
            
            // Save the RSS feed to the file system
            fs.writeFileSync("feeds/nitter_combined_feed.xml", feedContent);

            await browser.close();
          }
          
          fetchFeed();' > fetch-feed.js

          # Run the Puppeteer script to fetch the feed and cookies
          node fetch-feed.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add feeds/nitter_combined_feed.xml
          git commit -m "Update mirrored Nitter RSS feed" || echo "No changes to commit"
          git push
