name: Mirror Nitter Feed

on:
  schedule:
    - cron: '0 */3 * * *'  # Schedule to run every 3 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest Firefox version from release notes title
        id: fetch_firefox_version
        run: |
          echo "Fetching the latest Firefox version from the release notes page title..."
          
          # Use curl to fetch the Firefox release notes page HTML
          RELEASE_NOTES_PAGE=$(curl -s https://www.mozilla.org/en-US/firefox/notes/)
          
          # Extract the version from the <title> tag, e.g., "Firefox 132.0.2, See All New Features..."
          FIREFOX_VERSION=$(echo "$RELEASE_NOTES_PAGE" | grep -oP '(?<=<title>Firefox )\d+\.\d+(\.\d+)?' | head -n 1)
          
          # Debugging: Print the extracted Firefox version
          echo "Extracted Firefox version: $FIREFOX_VERSION"
          
          # Ensure we have a valid version
          if [[ -z "$FIREFOX_VERSION" ]]; then
            echo "Error: Could not extract Firefox version from the title."
            exit 1
          fi
          
          # Set the User-Agent string using the extracted version
          echo "USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:$FIREFOX_VERSION) Gecko/20100101 Firefox/$FIREFOX_VERSION" >> $GITHUB_ENV
          echo "Firefox User-Agent string set for Windows: $USER_AGENT"

      - name: Fetch combined Nitter RSS feed with dynamic Firefox User-Agent
        run: |
          echo "Fetching the combined Nitter RSS feed using the following User-Agent:"
          echo "$USER_AGENT"
          
          # Fetch the combined RSS feed using the dynamically generated Firefox User-Agent
          curl -s -A "$USER_AGENT" "https://nitter.poast.org/yuki_sakuna,ksononair,95rn16,hanamiya_rica/rss" -o feeds/nitter_combined_feed.rss
          
          echo "Feed successfully fetched and saved to feeds/nitter_combined_feed.rss"

      - name: Commit and push changes
        run: |
          echo "Checking if any changes need to be committed..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git diff --exit-code
          if [ $? -eq 1 ]; then
            echo "Changes detected, committing and pushing the updated RSS feed..."
            git add feeds/nitter_combined_feed.rss
            git commit -m "Update mirrored Nitter RSS feed"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
