name: Mirror nitter Feed

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create feeds directory
        run: |
          mkdir -p feeds

      - name: Fetch feed
        run: |
          curl -sf "https://xcancel.com/firefox/rss" -o feeds/nitter.rss

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add feeds/nitter.rss
          git commit -m "Update feed" || echo "No changes to commit"
          git push
