name: Mirror Nitter Feed
on:
  schedule:
    - cron: '0 */3 * * *'  # Schedule to run every 3 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch combined Nitter RSS feed
        run: |
          # Fetch the combined RSS feed (single-line XML document)
          curl -s "https://nitter.poast.org/yuki_sakuna,ksononair,95rn16,hanamiya_rica/rss" -o feeds/nitter_combined_feed.xml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add feeds/nitter_combined_feed.xml
          git commit -m "Update mirrored Nitter RSS feed" || echo "No changes to commit"
          git push

          else
            echo "No changes detected. Skipping commit and push."
          fi
