name: Modify ototoy RSS Feed

on:
  schedule:
    - cron: 0 * * * *

jobs:
  modify-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch and modify RSS feed
        run: |
          curl -s https://politepol.com/fd/fOrdd29ndzQa.xml > original.xml
          xmllint --xpath "//channel/item" original.xml | while read item; do
            title=$(echo "$item" | xmllint --xpath "string(//title)" -)
            description=$(echo "$item" | xmllint --xpath "string(//description)" -)
            link=$(echo "$item" | xmllint --xpath "string(//link)" -)
            echo "Modifying item with title '$title'"
            sed -i "/$title/,/<\/item>/ s|$title|$title / $description|" original.xml
            sed -i "/$title/,/<\/item>/ s|$link|https://youtube.com/results?search_query=$title / $description|" original.xml
            sed -i "/$title/,/<\/item>/ s|$description|$link|" original.xml
          done
          mkdir -p feeds
          mv original.xml feeds/ototoy-rss.xml

      - name: Commit modified RSS feed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add feeds/ototoy-rss.xml
          git commit -m "Update ototoy-rss.xml"

      - name: Push modified RSS feed
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
