name: Ubuntu Runner System Info

on:
  workflow_dispatch:

jobs:
  show-system-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Print basic CPU info
        run: |
          echo "=== CPU ==="
          echo "nproc (logical CPUs): $(nproc)"
          echo "lscpu summary:"
          lscpu

      - name: Print memory summary
        run: |
          echo "=== MEMORY ==="
          free -h
          echo
          echo "Detailed /proc/meminfo (first 20 lines):"
          sed -n '1,20p' /proc/meminfo

      - name: Available memory in bytes
        run: |
          # Available memory (preferred) in kB from /proc/meminfo, then convert to bytes
          avail_kb=$(awk '/^MemAvailable:/ {print $2}' /proc/meminfo)
          if [ -z "$avail_kb" ]; then
            echo "MemAvailable not found; falling back to MemFree+Buffers+Cached"
            memfree_kb=$(awk '/^MemFree:/ {free=$2} /^Buffers:/ {buf=$2} /^Cached:/ {cache=$2} END {print free+buf+cache}' /proc/meminfo)
            avail_kb=$memfree_kb
          fi
          avail_bytes=$((avail_kb * 1024))
          echo "Available memory: ${avail_kb} kB (${avail_bytes} bytes)"

      - name: Top memory-consuming processes
        run: |
          echo "=== Top memory-consuming processes (RSS) ==="
          ps aux --sort=-rss | awk 'NR==1 || NR<=11 {print $0}' 

      - name: Disk usage (for context)
        run: |
          echo "=== Disk usage ==="
          df -h /

      - name: Environment and limits
        run: |
          echo "=== ulimit & env ==="
          ulimit -a || true
          echo
          echo "Runner environment (selected vars):"
          env | egrep 'RUNNER|GITHUB|HOME|USER' || true
